---
- name: Set timezone
  community.general.timezone:
    name: "{{ base_timezone }}"
  when: base_timezone | length > 0

- name: Ensure extra packages are present
  ansible.builtin.apt:
    name: "{{ base_extra_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: base_extra_packages | length > 0
